AWSTemplateFormatVersion: '2010-09-09'
Description: Parent Stack that Deploys VPC and EC2 Instance

Resources:
  VPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: "https://s3.amazonaws.com/iambucketraunakb/VPC.yaml"

  EC2Stack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: "https://s3.amazonaws.com/iambucketraunakb/EC2.yaml"
      Parameters:
        VPCID: !GetAtt VPCStack.Outputs.VPCID
